---
mariadb_cluster_name: "cloudstack_testenv"
mariadb_root_password: "Test123$"
mariadb_cluster: true
mariadb_sst_user: sstuser
mariadb_sst_password: sstpass
mariadb_clustercheck_user: clustercheck
mariadb_clustercheck_password: clustercheck
mariadb_cluster_singlewriter: true
