---
host_roles: [ "base", "network_vxlanevpn", "service_ceph", "service_cloudstack" ]
#host_roles: [ "service_cloudstack" ]
cloudstack_ceph_fs: "cloudstack"
cloudstack_mgmt_interface: "hypervisor"
cloudstack_version: "4.21"

