---

# To run, pass the group name to the --limit parameter which contains all the MariaDB hosts in the cluster
# Optional variables:
#   -e mariadb_ignore_offline_nodes=true
#      In some circumstances you may need to bring up a cluster that has some nodes down.  Passing
#      this flag will accomplish that.
#   -e mariadb_start_all_nodes=false
#      In some cases you may not want all nodes to be started, if this flag is specified it will
#      only start the most up to date node if no other nodes are running.

- hosts: all
  become: no
  gather_facts: False
  tasks:
  - name: make sure --limit was passed to ansible
    fail:
      msg: "you must use -l or --limit"
    when: ansible_limit is not defined
    run_once: true
    delegate_to: localhost

- hosts: all
  module_defaults:
    ansible.builtin.setup:
      gather_subset: all
      gather_timeout: 10
  become: yes
  tasks:
  - import_tasks: "tasks/cluster-start.yml"



