---
- name: install apache/mod_ssl/php
  yum:
    name: [ "httpd", "mod_ssl", "mod_md" ]
    state: latest

- name: open up http ports
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}"
    state: enabled
  with_items:
    - "80/tcp"
    - "443/tcp"

- name: See if welcome.conf consists of only comments or blank lines
  command:
    cmd: 'grep -E -q -v "(^#.*|^$)" /etc/httpd/conf.d/welcome.conf'
  register: welcome_uncommented
  changed_when: false
  failed_when: false

- name: Make sure all lines in welcome.conf are commented out
  command:
    cmd: 'sed -E -i -e "s/^([^#].+)$/#\1/" /etc/httpd/conf.d/welcome.conf'
    warn: false
  when: welcome_uncommented.rc == 0
  notify: httpd_restart

- name: set proper ssl options
  template:
    src: http_ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: add security settings
  copy:
    src: http_security.conf
    dest: /etc/httpd/conf.d/security.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: configure logging to go to syslog
  copy:
    src: http_log.conf
    dest: /etc/httpd/conf.d/log.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

# See https://www.server-world.info/en/note?os=CentOS_8&p=httpd2&f=1
- name: Support ACME authentication for letsencrypt via mod_md
  copy:
    src: http_acme.conf
    dest: /etc/httpd/conf.d/acme.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: Allow httpd to connect outbound (needed for letsencrypt)
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: SELinux module for mod_md (needed for letsencrypt)
  import_tasks: "{{ playbook_dir }}/common/tasks/semodule.yml"
  vars:
    selinux_module_name: httpd-md
    selinux_module_file: selinux_httpd_mod_md.pp

- name: comment out error log setting in httpd.conf
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: ErrorLog
    line: '# ErrorLog "logs/error_log"'
  notify: httpd_restart

- name: add web logging config to /etc/rsyslog.conf
  copy:
    src: rsyslog_apache.conf
    dest: /etc/rsyslog.d/apache.conf
    owner: root
    group: root
    mode: 0644
  notify: rsyslog_restart

- name: logrotate for httpd
  copy:
    src: logrotate_http
    dest: /etc/logrotate.d/http
    owner: root
    group: root
    mode: 0644

- name: systemd - enable and start httpd
  service:
    name: httpd
    state: started
    enabled: yes
