---
- name: "Retrieve ceph pools"
  shell: "ceph osd pool ls -f json"
  register: ceph_existing_pools

- name: "Create pools"
  include_tasks: ceph-pool-create.yml
  vars:
    pool_name: "{{ item.name }}"
    pool_replica: "{{ item.replica|default(3) }}"
    pool_min_size: "{{ item.min_size|default(2) }}"
    pool_bulk: "{{ item.bulk|default(true) }}"
    pool_application: "rbd"
  with_items: "{{ ceph_pools }}"
  when: item.name not in ceph_existing_pools.stdout|from_json
  run_once: true
