---
- name: "See if NFS is desired"
  set_fact:
    ceph_nfs_exports: "{{ ceph_fs|default([]) | selectattr('nfs', 'defined') | selectattr('nfs', 'equalto', true) | map(attribute='name') | list }}"

- name: Install NFS dependencies
  when: ceph_nfs_exports | length > 0
  ansible.builtin.apt:
    pkg:
      - "libcephfs2"
      - "nfs-ganesha"
      - "nfs-ganesha-ceph"
    state: present

- name: "UFW: Allow NFSv4 traffic"
  community.general.ufw:
    rule: allow
    port: 2049
    proto: tcp
    # Only public network is needed

- name: "Write Ganesha configuration"
  template:
    src: nfs.conf.j2
    dest: "/etc/ganesha/ganesha.conf"
    mode: 660
    owner: root
    group: root
  notify: restart_ganesha

- name: "Ensure Ganesha is enabled and started"
  service:
    name: nfs-ganesha
    enabled: true
    state: started
