---
- name: "ensure MDS directory exists"
  file:
    path: "/var/lib/ceph/mds/ceph-{{ inventory_hostname | split('.') | first }}"
    state: directory
    owner: ceph

- name: "see if MDS keyring exists"
  stat:
    path: "/var/lib/ceph/mds/ceph-{{ inventory_hostname | split('.') | first }}/keyring"
  register: mds_keyring

- name: "Create MDS keyring"
  shell: "ceph-authtool --create-keyring /var/lib/ceph/mds/ceph-{{ inventory_hostname | split('.') | first }}/keyring --gen-key -n mds.{{ inventory_hostname | split('.') | first }}"
  when: not mds_keyring.stat.exists

- name: "Make sure permissions are proper"
  file:
    path: "{{ item }}"
    owner: ceph
  with_items:
    - "/var/lib/ceph/mds/ceph-{{ inventory_hostname | split('.') | first }}/keyring"

- name: "Import keyring"
  shell: ceph auth add mds.{{ inventory_hostname | split('.') | first }} osd "allow rwx" mds "allow *" mon "allow profile mds" -i /var/lib/ceph/mds/ceph-{{ inventory_hostname | split('.') | first }}/keyring
  when: not mds_keyring.stat.exists

- name: "Ensure ceph-mdsis enabled and started"
  service:
    name: "ceph-mds@{{ inventory_hostname | split('.') | first }}"
    state: started
    enabled: true

- name: "UFW: Allow ceph mds traffic"
  community.general.ufw:
    rule: allow
    port: 6800:7568
    proto: tcp
