---
- name: "Check to see if monitor configuration exists"
  stat:
    path: "/var/lib/ceph/mon/ceph-{{ inventory_hostname|split('.')|first }}"
  register: ceph_mon_configured

- name: "UFW: Allow ceph monitor traffic v1"
  community.general.ufw:
    rule: allow
    port: 6789
    proto: tcp
    # Only public network is needed

- name: "UFW: Allow ceph monitor traffic v2"
  community.general.ufw:
    rule: allow
    port: 3300
    proto: tcp
    # Only public network is needed

- name: "monitor add"
  include_tasks: "ceph-mon-add.yml"
  when: not ceph_mon_configured.stat.exists

- name: "Ensure ceph-mon is enabled and started"
  service:
    name: "ceph-mon@{{ inventory_hostname | split('.') | first }}"
    state: started
    enabled: true

- name: "Make sure the mgr data directory exists"
  file:
    path: "/var/lib/ceph/mgr/ceph-{{ inventory_hostname | split('.') | first }}"
    state: directory

- name: "Make sure the mgr has a keyring"
  stat:
    path: "/var/lib/ceph/mgr/ceph-{{ inventory_hostname | split('.') | first }}/keyring"
  register: mgr_keyring

- name: "Make the keyring"
  when: not mgr_keyring.stat.exists
  shell: "ceph auth get-or-create mgr.{{ inventory_hostname | split('.') | first }} mon 'allow profile mgr' osd 'allow *' mds 'allow *' -o /var/lib/ceph/mgr/ceph-{{ inventory_hostname | split('.') | first }}/keyring"

- name: "Make sure permissions are proper"
  file:
    path: "{{ item }}"
    owner: ceph
  with_items:
    - "/var/lib/ceph/mgr/ceph-{{ inventory_hostname | split('.') | first }}/keyring"

- name: "UFW: Allow ceph mgr traffic"
  community.general.ufw:
    rule: allow
    port: "6800:7300"
    proto: tcp
    dest: "{{ ceph_mon_ip }}"

- name: "Ensure ceph-mgr is enabled and started"
  service:
    name: "ceph-mgr@{{ inventory_hostname | split('.') | first }}"
    state: started
    enabled: true

- name: "Ceph: check auth_allow_insecure_global_id_reclaim"
  shell: ceph config get mon auth_allow_insecure_global_id_reclaim
  register: ceph_insecure_global_id
  changed_when: false
  run_once: true

- name: "Ceph: set auth_allow_insecure_global_id_reclaim to false"
  shell: "ceph config set mon auth_allow_insecure_global_id_reclaim false"
  when: ceph_insecure_global_id.stdout_lines|first == "true"
  run_once: true

- name: "Ceph: enable osd pg autoscaling by default"
  shell: "ceph config set global osd_pool_default_pg_autoscale_mode on"
  when: ceph_bootstrap

- name: "Ceph: enable msgr2 protocol"
  shell: "ceph mon enable-msgr2"
  when: ceph_bootstrap
