---

- name: "Create data and metadata pools for {{ fs_name }}"
  include_tasks: ceph-pool-create.yml
  vars:
    pool_name: "{{ item.name }}"
    pool_replica: 3
    pool_min_size: 2
    pool_bulk: "{{ item.bulk }}"
    pool_application: "cephfs"
  with_items:
    - { "name": "{{ fs_name }}_data", "bulk": true }
    - { "name": "{{ fs_name }}_metadata", "bulk": false }

- name: "Create fs {{ fs_name }}"
  shell: "ceph fs new {{ fs_name }} {{ fs_name }}_metadata {{ fs_name }}_data"

