---
- name: "Retrieve ceph pools"
  shell: "ceph osd pool ls -f json"
  register: ceph_existing_pools
  run_once: true
  changed_when: false

- name: "Create pools"
  include_tasks: ceph-pool-create.yml
  vars:
    pool_name: "{{ pool.name }}"
    pool_replica: "{{ pool.replica|default(3) }}"
    pool_min_size: "{{ pool.min_size|default(2) }}"
    pool_bulk: "{{ pool.bulk|default(true) }}"
    pool_application: "rbd"
  with_items: "{{ ceph_pools }}"
  loop_control:
    loop_var: pool
  when: pool.name not in ceph_existing_pools.stdout|from_json
  run_once: true
