---

- name: Install NFS dependencies
  ansible.builtin.apt:
    pkg:
      - "libcephfs2"
      - "nfs-ganesha"
      - "nfs-ganesha-ceph"
    state: present

- name: "UFW: Allow NFSv4 traffic"
  community.general.ufw:
    rule: allow
    port: 2049
    proto: tcp
    # Only public network is needed

- name: "Write Ganesha configuration"
  template:
    src: nfs.conf.j2
    dest: "/etc/ganesha/ganesha.conf"
    mode: 660
    owner: root
    group: root
  notify: restart_ganesha

- name: "Ensure Ganesha is enabled and started"
  service:
    name: nfs-ganesha
    enabled: true
    state: started
