---
- name: "Retrieve ceph filesystems"
  shell: "ceph fs ls -f json"
  register: ceph_existing_filesystems
  changed_when: false
  run_once: true

- name: "Create ceph filesystems"
  include_tasks: ceph-fs-create.yml
  vars:
    fs_name: "{{ fs.name }}"
    fs_nfs: "{{ fs.nfs }}"
  with_items: "{{ ceph_fs }}"
  loop_control:
    loop_var: fs
  when: fs.name not in ceph_existing_filesystems.stdout|from_json|map(attribute='name')|list
  run_once: true
