---
- name: "Retrieve ceph filesystems"
  shell: "ceph fs ls -f json"
  register: ceph_existing_filesystems

- name: "Create ceph filesystems"
  include_tasks: ceph-fs-create.yml
  vars:
    fs_name: "{{ item.name }}"
  with_items: "{{ ceph_fs }}"
  when: item.name not in ceph_existing_filesystems.stdout|from_json
  run_once: true
