---
- name: Make cluster sync user for SST
  community.mysql.mysql_user:
    login_unix_socket: "{{ mariadb_sock }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    check_implicit_admin: true
    column_case_sensitive: false
    name: "{{ mariadb_sst_user }}"
    password: "{{ mariadb_sst_password }}"
    host: "localhost"
    priv: "*.*:RELOAD,PROCESS,LOCK TABLES,BINLOG MONITOR,REPLICATION CLIENT"

- name: Make cluster health check user
  community.mysql.mysql_user:
    login_unix_socket: "{{ mariadb_sock }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    check_implicit_admin: true
    column_case_sensitive: false
    name: "{{ mariadb_clustercheck_user }}"
    password: "{{ mariadb_clustercheck_password }}"
    host: "localhost"
    priv: "*.*:PROCESS"
