---
- name: Install MariaDB AppStream
  dnf:
    name: "@mariadb:10.11"
    state: installed

- name: Install MariaDB Server
  dnf:
    name: [ "mariadb-server", "python3-PyMySQL" ]
    state: installed

- name: Install configuration
  template:
    src: zcustom_base.cnf
    dest: /etc/my.cnf.d/zcustom_base.cnf
    owner: root
    group: root
    mode: 0644
  notify: mysql_restart

- name: Create mysql tmp directory
  file:
    path: /var/lib/mysql-tmp
    state: directory
    owner: mysql
    group: mysql
    mode: 0750
    setype: mysqld_db_t
  notify: mysql_restart

- name: Set SELinux file context appropriately for /var/lib/mysql-tmp
  sefcontext:
    state: present
    setype: mysqld_db_t
    target: /var/lib/mysql-tmp(/.*)?

- name: Start and Enable MariaDB
  service:
    name: mariadb
    enabled: true
    state: started

- name: Set root password for MariaDB for localhost
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ vault_root_password }}"
    check_implicit_admin: true
    column_case_sensitive: false
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: root
    password: "{{ vault_root_password }}"
    host: "{{ item }}"
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: Remove root password for MariaDB for non-localhost users
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: "{{ vault_root_password }}"
    check_implicit_admin: true
    column_case_sensitive: false
    name: root
    host: "{{ inventory_hostname }}"
    state: absent

- name: Remove all anonymous users from MariaDB
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: "{{ vault_root_password }}"
    check_implicit_admin: true
    column_case_sensitive: false
    name: ''
    host_all: yes
    state: absent

- name: enable or disable mariadb port depending on if external access is allowed
  firewalld:
    immediate: yes
    permanent: yes
    port: "3306/tcp"
    state: "{{ 'enabled' if mariadb_external_access else 'disabled' }}"

