---
all:
  hosts:
  children:
    wordpress:
      hosts:
        bradhouse.dev:
          ssh_port:     5022
          ansible_user: infra
          host_roles:   [ "base", "service_apache", "service_php" ]
