---
all:
  hosts:
  children:
    wordpress:
      hosts:
        bradhouse.dev:
          ansible_port: 5022
          ansible_user: infra
          ansible_host: bradhouse.dev
          host_roles: [ "base", "apache" ]
