---
all:
  hosts:
  children:
    dbonly:
      hosts:
        test.bradhouse.dev:
          ssh_port:               2022
          ansible_user:           infra
          host_roles:             [ "base", "service_mariadb" ]
    wordpress:
      hosts:
        bradhouse.dev:
          ssh_port:               5022
          ansible_user:           infra
          host_roles:             [ "base", "service_apache", "service_php", "service_mariadb", "app_wordpress" ]
          wordpress_install_path: "/var/www/bradhouse.dev/public"
