---
wordpress:
  hosts:
    bradhouse.dev:
      ssh_port:                 5022
      superuser:                infra
      host_roles:               [ "base", "service_apache", "service_php", "service_mariadb", "app_wordpress" ]
      base_autoupdate:          true
      apache_letsencrypt:       true
      wordpress_install_path:   "/var/www/bradhouse.dev/public"
      wordpress_domain:         "bradhouse.dev"
      wordpress_domain_aliases: [ "www.bradhouse.dev", "brad-house.com", "www.brad-house.com" ]
      wordpress_db_user:        "wordpress"
      wordpress_db_name:        "wordpress"
      wordpress_db_pass:        "{{ vault_bradhouse_wordpress_db_pass }}"
sonic:
  hosts:
    sw1.testenv.bradhouse.dev:
      ansible_host: 192.168.1.189
    sw2.testenv.bradhouse.dev:
      ansible_host: 192.168.1.129
    swmgmt.testenv.bradhouse.dev:
      ansible_host: 192.168.1.55
cloudstack:
  hosts:
    node1.testenv.bradhouse.dev:
      ansible_host: 192.168.1.220
    node2.testenv.bradhouse.dev:
      ansible_host: 192.168.1.173
    node3.testenv.bradhouse.dev:
      ansible_host: 192.168.1.135
    node4.testenv.bradhouse.dev:
      ansible_host: 192.168.1.183
