---
all:
  hosts:
    test:
      ansible_host: 192.168.1.220
      ansible_user: brad
      ansible_password: "Test123$"
  children:
    wordpress:
      hosts:
        bradhouse.dev:
          ssh_port:                 5022
          superuser:                infra
          host_roles:               [ "base", "service_apache", "service_php", "service_mariadb", "app_wordpress" ]
          base_autoupdate:          true
          apache_letsencrypt:       true
          wordpress_install_path:   "/var/www/bradhouse.dev/public"
          wordpress_domain:         "bradhouse.dev"
          wordpress_domain_aliases: [ "www.bradhouse.dev", "brad-house.com", "www.brad-house.com" ]
          wordpress_db_user:        "wordpress"
          wordpress_db_name:        "wordpress"
          wordpress_db_pass:        "{{ vault_bradhouse_wordpress_db_pass }}"
    sonic:
      hosts:
        sw1.testenv.bradhouse.dev:
          ansible_host: 192.168.1.189
          ansible_user: admin
        sw2.testenv.bradhouse.dev:
          ansible_host: 192.168.1.129
          ansible_user: admin
        swmgmt.testenv.bradhouse.dev:
          ansible_host: 192.168.1.55
          ansible_user: admin
    cloudstack:
      hosts:
        node1.testenv.bradhouse.dev:
          ansible_host: 192.168.1.220
          ansible_user: brad
        node2.testenv.bradhouse.dev:
          ansible_host: 192.168.1.173
          ansible_user: brad
        node3.testenv.bradhouse.dev:
          ansible_host: 192.168.1.135
          ansible_user: brad
        node4.testenv.bradhouse.dev:
          ansible_host: 192.168.1.183
          ansible_user: brad
