---
- name: chrony_restart
  service:
    name: chronyd
    state: restarted

- name: journald_restart
  service:
    name: systemd-journald
    state: restarted

- name: rsyslog_restart
  service:
    name: rsyslog
    state: restarted

- name: sshd_restart
  service:
    name: "{{ 'sshd' if ansible_os_family == 'RedHat' else 'ssh' }}"
    state: restarted

- name: firewall_reload
  service:
    name: firewalld
    state: restarted

- name: set_hostname
  command: "hostnamectl set-hostname {{ inventory_hostname }}"

- name: fail2ban_restart
  service:
    name: fail2ban
    state: restarted

- name: auditd_reload
  service:
    name: auditd
    state: restarted
    use: service

- name: update_grub
  command: "{{ 'grub2-mkconfig -o /boot/grub2/grub.cfg' if ansible_os_family == 'RedHat' else 'grub-mkconfig -o /boot/grub/grub.cfg' }}"

- name: reboot
  reboot:
    msg: "rebooting now"
    connect_timeout: 10
    post_reboot_delay: 60
