---
- name: "Retrieve cloudstack installed version"
  shell: "dpkg -l cloudstack-common | tail -n 1 | awk '{ print $3 }' | cut -d . -f 1-3"
  register: cloudstack_version_query
  changed_when: false

- name: "Set version"
  set_fact:
    cloudstack_major: "{{ cloudstack_version_query.stdout_lines[0].split('.')[0] }}"
    cloudstack_minor: "{{ cloudstack_version_query.stdout_lines[0].split('.')[1] }}"
    cloudstack_release: "{{ cloudstack_version_query.stdout_lines[0].split('.')[2] }}"

- name: "Secondary: Make mount directory"
  file:
    path: /mnt/tmp
    state: directory
    mode: "777"
  changed_when: false

- name: Temporarily mount secondary
  shell: "mount -t ceph admin@.{{ cloudstack_ceph_fs }}=/ /mnt/tmp"
  changed_when: false

- name: "See if template directory exists"
  stat:
    path: /mnt/tmp/template
  register: templatedir

# TODO: Determine how to update the system vm image on upgrades
- name: "Generate system vm image"
  shell: "/usr/share/cloudstack-common/scripts/storage/secondary/cloud-install-sys-tmplt -m /mnt/tmp -u http://download.cloudstack.org/systemvm/{{ cloudstack_major }}.{{ cloudstack_minor }}/systemvmtemplate-{{ cloudstack_major }}.{{ cloudstack_minor }}.{{ cloudstack_release }}-x86_64-kvm.qcow2.bz2 -h kvm -s '{{ cloudstack_mgmt_key }}' -F"
  when: not templatedir.stat.exists

- name: Unmount
  shell: "umount /mnt/tmp"
  changed_when: false
