---
cloudstack_kvm:
  hosts:
    node1.testenv.bradhouse.dev:
      # Configured in cloudstack_mgmt
    node2.testenv.bradhouse.dev:
      # Configured in cloudstack_mgmt
    node3.testenv.bradhouse.dev:
      # Configured in cloudstack_mgmt
    node4.testenv.bradhouse.dev:
      ansible_host: 192.168.1.84
      ceph_osd_chassis: "microcloud1"
      network_vtep_ip:  "172.16.0.104/24"
      network_underlay_asn: 4220000004
      hypervisor_ip: "10.10.100.5/24"
      ceph_ip: "10.10.200.5/24"
      public_ip: "192.168.1.84/24"
    node5.testenv.bradhouse.dev:
      ansible_host: 192.168.1.85
      ceph_osd_chassis: "microcloud1"
      network_vtep_ip:  "172.16.0.105/24"
      network_underlay_asn: 4220000005
      hypervisor_ip: "10.10.100.6/24"
      ceph_ip: "10.10.200.6/24"
      public_ip: "192.168.1.85/24"
    node6.testenv.bradhouse.dev:
      ansible_host: 192.168.1.86
      ceph_osd_chassis: "microcloud1"
      network_vtep_ip:  "172.16.0.106/24"
      network_underlay_asn: 4220000006
      hypervisor_ip: "10.10.100.7/24"
      ceph_ip: "10.10.200.7/24"
      public_ip: "192.168.1.86/24"
    node7.testenv.bradhouse.dev:
      ansible_host: 192.168.1.87
      ceph_osd_chassis: "microcloud1"
      network_vtep_ip:  "172.16.0.107/24"
      network_underlay_asn: 4220000007
      hypervisor_ip: "10.10.100.8/24"
      ceph_ip: "10.10.200.8/24"
      public_ip: "192.168.1.87/24"
    node8.testenv.bradhouse.dev:
      ansible_host: 192.168.1.88
      ceph_osd_chassis: "microcloud1"
      network_vtep_ip:  "172.16.0.108/24"
      network_underlay_asn: 4220000008
      hypervisor_ip: "10.10.100.9/24"
      ceph_ip: "10.10.200.9/24"
      public_ip: "192.168.1.88/24"
  vars:
    host_roles: [ "base", "network_vxlanevpn", "service_ceph", "service_cloudstack" ]
    #host_roles: [ "service_cloudstack" ]
    network_underlay_interfaces:
      - driver: "mlx5_core"
        speed: 25000
        fec: "rs"
        autonegotiation: false
    network_vxlans:
      # Management / Hypervisor network
      - vni: 100
        ifname: "hypervisor"
        mtu: 9000
      # Storage network
      - vni: 200
        ifname: "ceph"
        mtu: 9000
      # Public network
      - vni: 2
        ifname: "public"
        mtu: 1500
    network_bridges:
      - name: "hypervisor"
        mtu: 9000
        stp: false
        vlan_aware: false
        addresses:
          - "{{ hypervisor_ip }}"
        # Route to Private Cloud which has a Private Gateway pointing to this address.
        routes:
          - to: "10.252.0.0/16"
            via: "10.10.100.99"
      - name: "ceph"
        mtu: 9000
        stp: false
        vlan_aware: false
        addresses:
          - "{{ ceph_ip }}"
      - name: "public"
        mtu: 1500
        stp: false
        vlan_aware: false
        addresses:
          - "{{ public_ip }}"
        routes:
          - to: "0.0.0.0/0"
            via: "192.168.1.1"
        nameservers:
          addresses:
            - 192.168.1.1
    cloudstack_ceph_fs: "cloudstack"
    cloudstack_mgmt_interface: "hypervisor"
    cloudstack_version: "4.21"
