---
freeipa_servers:
  hosts:
    ipa1.ipa.pc.testenv.bradhouse.dev:
      pc_host_addresses:
        - "10.252.3.11/24"
    ipa2.ipa.pc.testenv.bradhouse.dev:
      pc_host_addresses:
        - "10.252.3.12/24"
    ipa3.ipa.pc.testenv.bradhouse.dev:
      pc_host_addresses:
        - "10.252.3.13/24"
  vars:
    host_roles: [ "base", "network_vxlanevpn", "service_freeipa" ]
    pc_host_gatewayv4: "10.252.3.1"
    service_freeipa_realm: "BRADHOUSE.DEV"
    service_freeipa_domain: "bradhouse.dev"
    service_freeipa_bind_user: "bind"
    service_freeipa_bind_pass: "Test123$"
    host_use_default_ip: true
    service_freeipa_idpsync_enable: true
    service_freeipa_idp_proxy: "http://secureproxy.proxy.pc.testenv.bradhouse.dev:8080"
    service_freeipa_idp_noproxy: [ ".pc.testenv.bradhouse.dev" ]
    service_freeipa_idpsync_idp_name: "Okta"
    service_freeipa_idpsync_provider: "okta"
    service_freeipa_idpsync_provider_domain: "trial-6940863.okta.com"
    service_freeipa_idpsync_clientid: "0oaw3g9uub1dGhi3t697"
    service_freeipa_idpsync_server: "ldapproxy.ldapproxy.pc.testenv.bradhouse.dev"
    service_freeipa_idpsync_binddn: "uid=bind@brad-house.com,ou=users,dc=trial-6940863,dc=okta,dc=com"
    service_freeipa_idpsync_bindpass: "Test123$"
    service_freeipa_idpsync_userdn: "ou=users,dc=trial-6940863,dc=okta,dc=com"
    service_freeipa_idpsync_groupdn: "ou=groups,dc=trial-6940863,dc=okta,dc=com"
    service_freeipa_idpsync_ignore_users:
      - "bind@brad-house.com"
    service_freeipa_idpsync_ignore_groups:
      - "Okta Administrators"
      - "Everyone"
    service_freeipa_enroll_user: "svc_enroll"
    service_freeipa_enroll_pass: "Test123$"
    service_freeipa_admin_pass: "Test123$"
    service_freeipa_dm_pass: "Test123$"

