---
dns:
  hosts:
    mirror1.mirror.pc.testenv.bradhouse.dev:
      network_interfaces:
        - name: "enp3s0"
          ifname: "enp3s0"
          addresses:
            - "10.252.2.11/24"
          routes:
            - to: "0.0.0.0/0"
              via: "10.252.2.1"
          nameservers:
            addresses: "{{ pc_nameservers }}"
  vars:
    host_roles: [ "base", "network_vxlanevpn", "service_mirror" ]
    mirror_bwlimit: 500
    mirror_destination: "/var/www"
    mirror_dns_email: "brad@brad-house.com"
    mirror_dns_provider: "godaddy"
    mirror_dns_apikey: "{{ godaddy_apikey }}"
    mirror_sites:
      # Mirror list: https://launchpad.net/ubuntu/+archivemirrors
      - id: "ubuntu"
        name: "Ubuntu Linux"
        type: "debmirror"
        host: "mirror.nodesdirect.com"
        remote_dir: "ubuntu"
        deb_dists: [ "jammy", "jammy-updates", "jammy-security", "noble", "noble-updates", "noble-security" ]
        deb_arch: [ "amd64", "arm64" ]
        deb_sections: [ "main", "main/installer", "multiverse", "multiverse/installer", "restricted", "restricted-installer", "universe", "universe/installer" ]

      # Mirror list: https://www.debian.org/mirror/list-full#US
      - id: "debian"
        name: "Debian"
        type: "debmirror"
        host: "mirror.nodesdirect.com"
        remote_dir: "debian"
        deb_dists: [ "bookworm", "bookworm-updates", "trixie", "trixie-updates" ]
        deb_arch: [ "amd64", "arm64" ]
        deb_sections: [ "main", "main/installer", "contrib", "non-free", "non-free-firmware" ]

      # Mirror list: https://mirrors.rockylinux.org/mirrormanager/mirrors
      - id: "rocky"
        name: "Rocky Linux"
        type: "rsync"
        host: "plug-mirror.rcac.purdue.edu"
        remote_dir: "rocky"
        rsync_exclude: [ "ppc64le/", "riscv64/", "s390x/", "8/", "8.*/", "9/", "9.*/" ]
        rsync_precheck_file: "fullfiletimelist-rocky"

      # Mirror list: https://mirrormanager.fedoraproject.org/mirrors/EPEL
      - id: "epel"
        name: "EPEL"
        type: "rsync"
        host: "archive.mci-1.serverforge.org"
        remote_dir: "fedora-epel"
        rsync_exclude: [ "ppc64le/", "riscv64/", "s390x/", "8/", "9/", "testing/" ]

