---
mirror:
  hosts:
    mirror1.mirror.pc.testenv.bradhouse.dev:
      pc_host_addresses:
        - "10.252.2.11/24"
      pc_host_gatewayv4: "10.252.2.1"
  vars:
    host_roles: [ "base", "network_vxlanevpn", "service_mirror" ]
    mirror_bwlimit: 500
    mirror_data_disk: "/dev/sdb"
    mirror_destination: "/var/www"
    mirror_dns_email: "brad@brad-house.com"
    mirror_dns_provider: "godaddy"
    mirror_dns_apikey: "{{ godaddy_apikey }}"
    mirror_sites:
      # Mirror list: https://mirrors.rockylinux.org/mirrormanager/mirrors
      - id: "rocky"
        name: "Rocky Linux"
        type: "rsync"
        host: "plug-mirror.rcac.purdue.edu"
        remote_dir: "rocky"
        rsync_exclude: [ "ppc64le/", "riscv64/", "s390x/", "8/", "8.*/", "9/", "9.*/" ]
        rsync_precheck_file: "fullfiletimelist-rocky"

      # Mirror list: https://mirrormanager.fedoraproject.org/mirrors/EPEL
      - id: "epel"
        name: "EPEL"
        type: "rsync"
        host: "mirror.nodesdirect.com"
        remote_dir: "epel"
        rsync_exclude: [ "ppc64le/", "riscv64/", "s390x/", "8/", "9/", "testing/" ]
        rsync_precheck_file: "fullfiletimelist-epel"

      # Mirror list: https://launchpad.net/ubuntu/+archivemirrors
      # westcoast try mirror.sfo12.us.leaseweb.net
      - id: "ubuntu"
        name: "Ubuntu Linux"
        type: "rsync"
        host: "mirror.nodesdirect.com"
        remote_dir: "ubuntu"
        rsync_firststage_exclude: [ "Packages*", "Sources*", "Release*", "InRelease" ]

      # Mirror list: https://www.debian.org/mirror/list-full#US
      - id: "debian"
        name: "Debian"
        type: "rsync"
        host: "mirror.nodesdirect.com"
        remote_dir: "debian"
        rsync_firststage_exclude: [ "Packages*", "Sources*", "Release*", "InRelease" ]
        rsync_exclude:
          - "arch-riscv64*"
          - "binary-riscv64/"
          - "*_riscv64.deb"
          - "*_riscv64.udeb"
          - "installer-riscv64/"
          - "Contents-riscv64*"
          - "Contents-udeb-riscv64*"
          - "arch-ppc64el*"
          - "binary-ppc64el/"
          - "*_ppc64el.deb"
          - "*_ppc64el.udeb"
          - "installer-ppc64el/"
          - "Contents-ppc64el*"
          - "Contents-udeb-ppc64el*"
          - "arch-mips64el*"
          - "binary-mips64el/"
          - "*_mips64el.deb"
          - "*_mips64el.udeb"
          - "installer-mips64el/"
          - "Contents-mips64el*"
          - "Contents-udeb-mips64el*"


