---
#commentfile.yml
# Helper script to check to make sure a configuration file contains only
# comments, and if not, to comment out all lines in the file.

# Vars:
#  - commentfile.path: Path to file on remote host to ensure contains only
#    comments.
#  - commentfile.notify: Notification to run if commentfile_path is modified.
#
# Usage Example:
#   Simple:
#   - import_tasks: "{{ playbook_dir }}/common/tasks/commentfile.yml"
#     vars:
#       commentfile:
#         path: "/etc/httpd/welcome.conf"
#         notify: "httpd_restart"
#
#   Complex:
#   - include_tasks: "{{ playbook_dir }}/common/tasks/commentfile.yml"
#     loop_control:
#       loop_var: commentfile
#     with_items:
#       - { path: "/etc/httpd/conf.d/welcome.conf",   notify: "httpd_restart" }
#       - { path: "/etc/httpd/conf.d/userdir.conf",   notify: "httpd_restart" }
#       - { path: "/etc/httpd/conf.d/autoindex.conf", notify: "httpd_restart" }

- name: "commentfile: Validate {{ commentfile.path }} consists of only comments or blank lines"
  command:
    cmd: "grep -E -q -v '(^#.*|^$)' {{ commentfile.path }}"
  register: commentfile_uncommented
  changed_when: false
  failed_when: false

- name: "commentfile: Comment out all lines in {{ commentfile.path }}"
  command:
    cmd: 'sed -E -i -e "s/^([^#].+)$/#\1/" {{ commentfile.path }}'
  when: commentfile_uncommented.rc == 0
  notify: "{{ commentfile.notify }}"
