---
# wordpress_backup=true/false
#  If true, go to https://console.developers.google.com/
#  Enable the google drive API.
#  Create a new project, name it "Wordpress Backup Client"
#  It will require you create an OAuth2 consent screen, add perms of "../auth/drive.file"
#  Create new credentials-> OAuth client id.  Application type should be "Desktop App".
#  You can name it "Wordpress Backup Client".
#  Run  wp gdrive auth  and enter in the id and secret, and go to the web page provided.
#  A code will be returned on the web page you need to enter back into the auth command.

- set_fact:
    gdrive_version: 3.9.1

- name: Check to see if WordPress is already installed
  stat:
    path: "{{ wordpress_install_path }}/wp-admin"
  register: wordpress_installed

- name: Ensure we fetch the most current wordpress release
  delegate_to: localhost
  become: no
  file:
    path: /tmp/wordpress-latest.tar.gz
    state: absent
  when: not wordpress_installed.stat.exists
  run_once: true

- name: Download the latest wordpress release
  delegate_to: localhost
  become: no
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress-latest.tar.gz
  when: not wordpress_installed.stat.exists
  run_once: true

- name: Ensure directory exists for web content
  file:
    path: "{{ wordpress_install_path }}"
    state: directory
    owner: apache
    group: apache
    mode: 0750
    setype: httpd_sys_content_t

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress-latest.tar.gz
    copy: yes
    dest: "{{ wordpress_install_path }}"
    owner: apache
    group: apache
    setype: httpd_sys_content_t
    extra_opts: [--strip-components=1]
  when: not wordpress_installed.stat.exists

- name: cleanup download
  delegate_to: localhost
  become: no
  file:
    path: /tmp/wordpress-latest.tar.gz
    state: absent
  when: not wordpress_installed.stat.exists
  run_once: true

- name: create database for wordpress
  mysql_db:
    login_user: root
    login_password: "{{ vault_root_password }}"
    name: "{{ wordpress_db_name }}"
    state: present

- name: create db user for wordpress
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ vault_root_password }}"
    check_implicit_admin: true
    name: "{{ wordpress_db_user }}"
    column_case_sensitive: false
    password: "{{ wordpress_db_pass }}"
    host: "{{ item }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: Create apache configuration for site
  template:
    src: apache_vhost.conf
    dest: "/etc/httpd/conf.d/{{ wordpress_domain }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: Check to see if the WordPress keys have been generated
  stat:
    path: "{{ wordpress_install_path }}/wp-config-keys.php"
  register: wordpress_keys

- name: Configure WordPress keys.  Must only run once as otherwise will kill all existing sessions.
  template:
    src: wp-config-keys.php
    dest: "{{ wordpress_install_path }}/wp-config-keys.php"
    owner: apache
    group: apache
    mode: 0640
    setype: httpd_sys_content_t
  when: not wordpress_keys.stat.exists

- name: Configure WordPress
  template:
    src: wp-config.php
    dest: "{{ wordpress_install_path }}/wp-config.php"
    owner: apache
    group: apache
    mode: 0640
    setype: httpd_sys_content_t

- name: Set up .htaccess for mod_rewrite rules
  copy:
    src: htaccess
    dest: "{{ wordpress_install_path }}/.htaccess"
    owner: apache
    group: apache
    mode: 0640
    setype: httpd_sys_content_t

- name: Set up selinux policies to allow some areas to be writable by apache
  sefcontext:
    state: present
    setype: httpd_sys_rw_content_t
    target: "{{ wordpress_install_path }}{{ item }}"
  with_items:
    - "/wp-content(/.*)?"

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv "{{ wordpress_install_path }}"
  register: restorecon
  changed_when: restorecon.stdout

- name: "wp-cli: check to see if it is installed"
  stat:
    path: "/usr/local/bin/wp"
  register: wpcli_installed

- name: "wp-cli: clear any cached download"
  delegate_to: localhost
  become: no
  file:
    path: /tmp/wp-cli.phar
    state: absent
  when: not wpcli_installed.stat.exists
  run_once: true

- name: "wp-cli: Download the latest release"
  delegate_to: localhost
  become: no
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /tmp/wp-cli.phar
  when: not wpcli_installed.stat.exists
  run_once: true

- name: "wp-cli: install"
  copy:
    src: /tmp/wp-cli.phar
    dest: /usr/local/bin/wp
    owner: root
    group: root
    mode: 0750
  when: not wpcli_installed.stat.exists

- name: "wp-cli: cleanup download"
  delegate_to: localhost
  become: no
  file:
    path: /tmp/wp-cli.phar
    state: absent
  when: not wpcli_installed.stat.exists
  run_once: true

- name: "wp-cli: check-update"
  command:
    argv:
      - "/usr/local/bin/wp"
      - "cli"
      - "check-update"
      - "--skip-plugins"
      - "--skip-themes"
  register: wpcli_checkupdate
  environment:
    PHP_INI_SCAN_DIR: /etc/php-cli.d/
  changed_when: false

- name: "wp-cli: update to the latest version"
  command:
    argv:
      - "/usr/local/bin/wp"
      - "cli"
      - "update"
      - "--stable"
      - "--yes"
      - "--skip-plugins"
      - "--skip-themes"
  environment:
    PHP_INI_SCAN_DIR: /etc/php-cli.d/
  when: "'WP-CLI is at the latest version' not in wpcli_checkupdate.stdout"

- name: "wp-cli: update all wp-cli packages"
  command:
    argv:
      - "/usr/local/bin/wp"
      - "package"
      - "update"
      - "--skip-plugins"
      - "--skip-themes"
  environment:
    PHP_INI_SCAN_DIR: /etc/php-cli.d/
  register: wpcliupdate
  changed_when: "'Nothing to install or update' not in wpcliupdate.stdout"

- name: "gdrive: Check Installation"
  stat:
    path: /usr/local/bin/gdrive-{{ gdrive_version }}
  register: gdrive

- name: "gdrive: Download"
  delegate_to: localhost
  become: no
  get_url:
    url: https://github.com/glotlabs/gdrive/releases/download/{{ gdrive_version }}/gdrive_linux-x64.tar.gz
    dest: /tmp/gdrive_linux-x64.tar.gz
  when: not gdrive.stat.exists
  run_once: true

- name: "gdrive: Extract"
  unarchive:
    src: /tmp/gdrive_linux-x64.tar.gz
    copy: yes
    dest: "/usr/local/bin/"
  when: not gdrive.stat.exists

- name: "gdrive: Install"
  shell: |
    mv /usr/local/bin/gdrive /usr/local/bin/gdrive-{{ gdrive_version }} && \
    chmod 755 /usr/local/bin/gdrive-{{ gdrive_version }}
  when: not gdrive.stat.exists

- name: "gdrive: cleanup download"
  delegate_to: localhost
  become: no
  file:
    path: /tmp/gdrive_linux-x64.tar.gz
    state: absent
  when: not gdrive.stat.exists
  run_once: true

- name: "Install wordpress update script for {{ wordpress_domain }}"
  template:
    src: wp-update.sh
    dest: "/usr/local/bin/wp-update-{{ wordpress_domain }}.sh"
    owner: root
    group: root
    mode: 0750

- name: "Install auto-update cron task for {{ wordpress_domain }}"
  template:
    src: cron_wp-update
    dest: "/etc/cron.d/wp-update-{{ wordpress_domain }}"
    owner: root
    group: root
    mode: 0644

- name: "Install gdrive helper script"
  template:
    src: gdrive.sh
    dest: "/usr/local/bin/gdrive.sh"
    owner: root
    group: root
    mode: 0750

- name: "Install wordpress backup script for {{ wordpress_domain }}"
  template:
    src: wp-backup.sh
    dest: "/usr/local/bin/wp-backup-{{ wordpress_domain }}.sh"
    owner: root
    group: root
    mode: 0750

- name: "Install wordpress restore script for {{ wordpress_domain }}"
  template:
    src: wp-restore.sh
    dest: "/usr/local/bin/wp-restore-{{ wordpress_domain }}.sh"
    owner: root
    group: root
    mode: 0750

- name: "Install auto-backup cron task for {{ wordpress_domain }}"
  template:
    src: cron_wp-backup
    dest: "/etc/cron.d/wp-backup-{{ wordpress_domain }}"
    owner: root
    group: root
    mode: 0644
