---
- name: sonic_bgp_update
  command: 'docker exec bgp /usr/local/bin/supervisorctl -c /etc/supervisor/supervisord.conf restart bgpd'
#  command: "docker restart bgp"

- name: sonic_reboot
  reboot:
    msg: "rebooting now"
    connect_timeout: 30
    post_reboot_delay: 120
