---

- name: retrieve platform
  shell: "show platform summary | grep 'Platform:' | cut -d : -f 2 | sed 's/ //g'"
  register: shellcmd
  failed_when: shellcmd.stdout | length == 0
  changed_when: False

- name: set platform fact
  set_fact:
    platform: "{{ shellcmd.stdout }}"

- name: retrieve hwsku
  shell: "show platform summary | grep 'HwSKU:' | cut -d : -f 2 | sed 's/ //g'"
  register: shellcmd
  failed_when: shellcmd.stdout | length == 0
  changed_when: False

- name: set hwsku fact
  set_fact:
    hwsku: "{{ shellcmd.stdout }}"

- name: Parse port_config.ini
  script: port_config_to_json.sh /usr/share/sonic/device/{{ platform }}/{{ hwsku }}/port_config.ini
  register: port_config
  failed_when: port_config.stdout | length == 0
  changed_when: False

- name: Load port config from JSON
  set_fact:
    ports: "{{ port_config.stdout|from_yaml }}"

- name: Try to determine port connection type
  script: port_connectors.sh
  register: port_connectors
  failed_when: port_connectors.stdout | length == 0
  changed_when: False

- name: Load port connectors from JSON
  set_fact:
    port_connectors: "{{ port_connectors.stdout|from_yaml }}"

- name: Make sure current running config is written to file
  shell: "config save -y"
  changed_when: false

- name: Load current system config
  slurp:
    src: "/etc/sonic/config_db.json"
  register: current_config_data

- name: Parse current system config
  set_fact:
    current_config: "{{ current_config_data.content|b64decode|from_yaml }}"

- name: Determine if configuration is too great for in-place update and may require a reboot
  set_fact:
    require_reboot: "{{ true if current_config.DEVICE_METADATA.localhost.docker_routing_config_mode|default('') != 'split' or current_config.DEVICE_METADATA.localhost.hostname != inventory_hostname or current_config.DEVICE_METADATA.localhost.type != 'LeafRouter' else false }}"

- debug:
    msg: "** REBOOT IS REQUIRED ** (will be performed automatically)"
  when: require_reboot

# Split generating into a step per section for easier debugging
- name: "Generate config: PORT"
  set_fact:
    port_json: "{{ lookup('template', 'PORT.j2') }}"

- name: "Generate config: INTERFACE"
  set_fact:
    interface_json: "{{ lookup('template', 'INTERFACE.j2') }}"

- name: "Generate config: LOOPBACK"
  set_fact:
    loopback_json: "{{ lookup('template', 'LOOPBACK.j2') }}"

- name: "Generate config: VLAN/VXLAN"
  set_fact:
    vxlan_json: "{{ lookup('template', 'VXLAN.j2') }}"

- name: "Generate config: STATIC_ROUTE"
  set_fact:
    static_route_json: "{{ lookup('template', 'STATIC_ROUTE.j2') }}"

- name: "Generate config: DEVICE_METADATA"
  set_fact:
    device_metadata_json: "{{ lookup('template', 'DEVICE_METADATA.j2') }}"

- name: "Parse config: PORT"
  set_fact:
    port: "{{ port_json|from_yaml }}"

- name: "Parse config: INTERFACE"
  set_fact:
    interface: "{{ interface_json|from_yaml }}"

- name: "Parse config: LOOPBACK"
  set_fact:
    loopback: "{{ loopback_json|from_yaml }}"

- name: "Parse config: VLAN/VXLAN"
  set_fact:
    vxlan: "{{ vxlan_json|from_yaml }}"

- name: "Parse config: STATIC_ROUTE"
  set_fact:
    static_route: "{{ static_route_json|from_yaml }}"

- name: "Parse config: DEVICE_METADATA"
  set_fact:
    device_metadata: "{{ device_metadata_json|from_yaml }}"

# NOTE we have to remove the STATIC_ROUTE table as it says it won't allow an empty table.
- name: Merge final config
  set_fact:
    config: |
      {{ current_config
          | ansible.utils.remove_keys(target=['^BGP_NEIGHBOR$', '^BGP_PEER_RANGE$', '^BGP_GLOBALS_AF_NETWORK$', '^BGP_NEIGHBOR_AF$', '^BGP_GLOBALS$', '^DEVICE_NEIGHBOR$'], matching_parameter='regex')
          | ansible.utils.remove_keys(target=['^VLAN$', '^VLAN_MEMBER$', '^VLAN_INTERFACE$', '^VXLAN_TUNNEL_MAP$', '^STATIC_ROUTE$'], matching_parameter='regex')
          | combine(port, list_merge='replace')
          | combine(interface, list_merge='replace')
          | combine(loopback, list_merge='replace')
          | combine(vxlan, list_merge='replace')
          | combine(static_route, list_merge='replace')
          | combine(device_metadata, recursive=True)
          | to_nice_json }}

- name: Write configuration
  copy:
    content: "{{ config }}"
    dest: /etc/sonic/config_db.json
# Normally writes in a different order which is fine since order doesn't matter
# for dictionaries, so we only need to mark as changed when we already know a
# reboot is required to possibly trigger that.  We will catch everything else
# when we commit the change.
  changed_when: require_reboot
  notify: "{{ 'sonic_reboot' }}"

- name: Write BGP configuration
  template:
    src: bgpd.conf.j2
    dest: /etc/sonic/frr/bgpd.conf
  notify: "{{ 'sonic_reboot' if require_reboot else 'sonic_bgp_update' }}"

# Fix VXLAN support for Broadcom Trident3 platforms as per
#  https://github.com/sonic-net/sonic-buildimage/issues/8371
- name: Find trident3 broadcom configuration
  find:
    paths: /usr/share/sonic/device/{{ platform }}/{{ hwsku }}/
    patterns: 'td3-*.bcm'
  register: td3bcm
  changed_when: false
  failed_when: false

- name: Add Broadcom VXLAN fix
  when: not td3bcm.failed and td3bcm.matched > 0
  lineinfile:
    path: "{{ td3bcm.files[0].path }}"
    line: "{{ item.key }}={{ item.value }}"
    regexp: "^{{ item.key }}=.*"
    state: present
  with_items:
    - { "key": "use_all_splithorizon_groups", "value": "1" }
    - { "key": "riot_enable", "value": "1" }
    - { "key": "sai_tunnel_support", "value": "1" }
    - { "key": "riot_overlay_l3_intf_mem_size", "value": "8192" }
    - { "key": "riot_overlay_l3_egress_mem_size", "value": "32768" }
    - { "key": "riot_overlay_ecmp_resilient_hash_size", "value": "16384" }
    - { "key": "flow_init_mode", "value": "1" }
    - { "key": "l3_ecmp_levels", "value": "2" }
  notify: sonic_reboot

# Do a graceful load of the new configuration if we aren't already rebooting.
- name: sonic_config_update
  command: "config replace --format CONFIGDB --verbose /etc/sonic/config_db.json"
  when: not require_reboot
  register: config_update
  changed_when: '"Generated patch: []" not in config_update.stdout'

