---
- name: httpd_restart
  service:
    name: httpd
    state: restarted

- name: rsyslog_restart
  service:
    name: rsyslog
    state: restarted

- name: fail2ban_restart
  service:
    name: fail2ban
    state: restarted
