---
- name: install php 8.2 stream
  dnf:
    name: '@php:8.2'
    state: present
  notify:
    - phpfpm_restart
    - httpd_restart

- name: install php-fpm and modules
  dnf:
    name: [ "php-fpm", "php-mysqlnd", "php-opcache", "php-gd", "php-xml",
            "php-mbstring", "php-pdo", "php-pecl-zip" ]
    state: latest
  notify:
    - phpfpm_restart
    - httpd_restart

- name: Configure apache to use php-fpm
  copy:
    src: apache_php.conf
    dest: /etc/httpd/conf.d/php.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: Install basic php preferences
  copy:
    src: local.ini
    dest: /etc/php.d/90-local.ini
    owner: root
    group: root
    mode: 0644
  notify: phpfpm_restart

- name: Install php hardening/security (noncli only)
  copy:
    src: security.ini
    dest: /etc/php.d/90-noncli-security.ini
    owner: root
    group: root
    mode: 0644
  notify: phpfpm_restart

- name: Install php-fpm default pool
  copy:
    src: php-fpm-pool-www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
  notify: phpfpm_restart

- name: systemd - enable and start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: "php-cli should use a different include directory"
  copy:
    src: profile_php-cli.sh
    dest: /etc/profile.d/php-cli.sh
    owner: root
    group: root
    mode: 0644

- name: "php-cli config directory"
  file:
    path: /etc/php-cli.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: get a list of aux configuration files for php. exclude noncli ones.
  shell: "ls /etc/php.d/ | grep -v noncli"
  register: php_configs
  changed_when: false

- name: symlink aux configs to php-cli.d
  file:
    state: link
    path: "/etc/php-cli.d/{{ item }}"
    src: "/etc/php.d/{{ item }}"
  with_items: "{{ php_configs.stdout_lines }}"

