---
ansible_host: 192.168.1.239
ceph_mon_ip: 10.10.100.2
mariadb_cluster_ip: 10.10.100.2
ceph_osd_chassis: "microcloud1"
network_vtep_ip:  "172.16.0.101/24"
network_underlay_asn: 4220000001
network_underlay_interfaces:
  - driver: "mlx5_core"
network_vxlan_interfaces:
  - name: "hypervisor"
    vni: 100
    mtu: 9000
    addresses:
      - "10.10.100.2/24"
  - name: "ceph"
    vni: 200
    mtu: 9000
    addresses:
      - "10.10.200.2/24"
  - name: "public"
    vni: 10010
    mtu: 1500
    addresses:
      - "10.0.0.91/24"
    nameservers:
      addresses:
        - 8.8.8.8
        - 2001:4860:4860::8888
network_interfaces:
  - ifname: "ens1"
    dhcp: "yes"
    routes:
      - to: "0.0.0.0/0"
        via: "192.168.1.1"
