---
ansible_host: 192.168.1.82
ceph_mon_ip: 10.10.100.3
mariadb_cluster_ip: 10.10.100.3
ceph_osd_chassis: "microcloud1"
network_vtep_ip:  "172.16.0.102/24"
network_underlay_asn: 4220000002
network_underlay_interfaces:
  - driver: "mlx5_core"
    speed: 25000
    fec: "rs"
    autonegotiation: false
network_vxlans:
  # Management / Hypervisor network
  - vni: 100
    bridge: "hypervisor"
    mtu: 9000
  # Storage network
  - vni: 200
    bridge: "ceph"
    mtu: 9000
  # Public network
  - vni: 2
    bridge: "public"
    mtu: 1500
network_bridges:
  - name: "hypervisor"
    mtu: 9000
    stp: false
    vlan_aware: false
    addresses:
      - "10.10.100.3/24"
  - name: "ceph"
    mtu: 9000
    stp: false
    vlan_aware: false
    addresses:
      - "10.10.200.3/24"
  - name: "public"
    mtu: 1500
    stp: false
    vlan_aware: false
    addresses:
      - "192.168.1.82/24"
    routes:
      - to: "0.0.0.0/0"
        via: "192.168.1.1"
    nameservers:
      addresses:
        - 8.8.8.8
        - 2001:4860:4860::8888
