---
ansible_host: 192.168.1.83
ceph_mon_ip: 10.10.100.4
mariadb_cluster_ip: 10.10.100.4
ceph_osd_chassis: "microcloud1"
network_vtep_ip:  "172.16.0.103/24"
network_underlay_asn: 4220000003
network_underlay_interfaces:
  - driver: "mlx5_core"
network_vxlan_interfaces:
  # Management / Hypervisor network
  - name: "hypervisor"
    vni: 100
    mtu: 1500
    addresses:
      - "10.10.100.4/24"
  # Storage network
  - name: "ceph"
    vni: 200
    mtu: 9000
    addresses:
      - "10.10.200.4/24"
  # Public network
  - name: "public"
    vni: 2
    mtu: 1500
    addresses:
      - "192.168.1.83/24"
    routes:
      - to: "0.0.0.0/0"
        via: "192.168.1.1"
    nameservers:
      addresses:
        - 8.8.8.8
        - 2001:4860:4860::8888

