---
ansible_host: 192.168.1.239
sonic_vxlan_vtep_ip: "172.16.0.2/32"
sonic_asn: "4210000002"
sonic_mgmt_vrf: true
# sonic_mclag:
#   group_id: 1
#   peer_ip: 172.16.0.1
#   source_ip: 172.16.0.2
sonic_interfaces:
  "1":
    layer3: true
    bgp_underlay: true
    description: "CloudStack1 port 2"
  "2":
    layer3: true
    bgp_underlay: true
    description: "CloudStack2 port 2"
  "3":
    layer3: true
    bgp_underlay: true
    description: "CloudStack3 port 2"
  "4":
    layer3: true
    bgp_underlay: true
    description: "CloudStack4 port 2"
  "5":
    layer3: true
    bgp_underlay: true
    description: "CloudStack5 port 2"
  "6":
    layer3: true
    bgp_underlay: true
    description: "CloudStack6 port 2"
  "7":
    layer3: true
    bgp_underlay: true
    description: "CloudStack7 port 2"
  "8":
    layer3: true
    bgp_underlay: true
    description: "CloudStack8 port 2"
  "15":
    description: "fakeinet ge-0/8"
    autoneg: "off"
    fec: "none"
    speed: "1000"
    layer3: true
  "16":
    description: "mgmtsw port 49"
    autoneg: "off"
    fec: "none"
    speed: "10000"
    layer3: true
    bgp_underlay: true
  "23":
    description: "PortChannel3 fw1 ge-0/9"
    autoneg: "off"
    fec: "none"
    speed: "1000"
  "24":
    description: "PortChannel4 fw2 ge-0/9"
    autoneg: "off"
    fec: "none"
    speed: "1000"
  "31":
    layer3: true
    bgp_underlay: true
    description: "torsw1 port 31"
    speed: "100000"
  "32":
    layer3: true
    bgp_underlay: true
    description: "torsw1 port 32"
    speed: "100000"

sonic_vlans:
  "10":
    vxlan: "10010"
    mtu: 1500
    ips: [ "10.0.0.72/24" ]
    layer3: true

sonic_portchannel:
  # "1":
  #   description: "management interface"
  #   interfaces:
  #     - "17"
  #     - "18"
  #   mtu: 1500
  #   layer3: true
  #   ips: [ "10.1.0.12/24" ]
  # "2":
  #   description: "redundant access port for management interface loop"
  #   interfaces:
  #     - "19"
  #     - "20"
  #   vlans:
  #     - vlan: 10
  #       mode: "untagged"
  "3":
    description: "fw1"
    interfaces:
      - "23"
    vlans:
      - vlan: 10
        mode: "untagged"
#     mclag: true
  "4":
    description: "fw2"
    interfaces:
      - "24"
    vlans:
      - vlan: 10
        mode: "untagged"
#     mclag: true

sonic_routes:
  - prefix: "8.8.4.4/32"
    nexthop: "10.1.1.1"

# Experimental
sonic_bgp_external: false

