---
ssh_port:                 5022
superuser:                infra
base_autoupdate:          true
apache_letsencrypt:       true
wordpress_install_path:   "/var/www/bradhouse.dev/public"
wordpress_domain:         "bradhouse.dev"
wordpress_domain_aliases: [ "www.bradhouse.dev", "brad-house.com", "www.brad-house.com" ]
wordpress_db_user:        "wordpress"
wordpress_db_name:        "wordpress"
wordpress_db_pass:        "{{ vault_bradhouse_wordpress_db_pass }}"
