---
sonic_bgp_ip: "172.16.0.1/32"
sonic_asn: "4210000001"
sonic_interfaces:
  "1": 
    layer3: true
    admin_status: "up"
    description: "CloudStack Node 1"
  "2":
    layer3: true
    admin_status: "up"
    description: "CloudStack Node 2"
  "3":
    layer3: true
    admin_status: "up"
    description: "CloudStack Node 2"
  "4":
    layer3: true
    admin_status: "up"
    description: "CloudStack Node 2"
  "5":
    layer3: true
    admin_status: "up"
    description: "CloudStack Node 2"
  "6":
    layer3: true
    admin_status: "up"
    description: "CloudStack Node 2"
  "7":
    layer3: true
    admin_status: "up"
    description: "CloudStack Node 2"
  "8":
    layer3: true
    admin_status: "up"
    description: "CloudStack Node 2"
  "9":
    admin_status: "up"
    description: "bootstrap port"
    vlans:
      - vlan: 2
        mode: "untagged"
  "46":
    layer3: true
    admin_status: "up"
    description: "Management Switch"
  "55":
    layer3: true
    admin_status: "up"
    description: "ToRSwitch 2 port 55"
  "56":
    layer3: true
    admin_status: "up"
    description: "ToRSwitch 2 port 56"
sonic_vlans:
  "2":
    ips: [ "10.0.0.71/24" ]
    vxlan: "10002"
    layer3: true
    mtu: 1500

