---
sonic_vxlan_vtep_ip: "172.16.0.1/32"
sonic_asn: "4210000001"
sonic_interfaces:
  "1":
    description: "PortChannel1 mgmt"
  "2":
    description: "PortChannel1 mgmt"
  "3":
    description: "PortChannel2 loop"
  "4":
    description: "PortChannel2 loop"
  "11":
    description: "bootstrap"
    autoneg: "off"
    fec: "none"
    speed: "10000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "13":
    description: "srx2"
    autoneg: "off"
    fec: "none"
    speed: "1000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "55":
    layer3: true
    description: "ToRSwitch 2 port 55"
#    vrf: "VrfUnderlay"

sonic_vlans:
  "2":
    vxlan: "10002"
#    mtu: 1500
#    ips: [ "10.0.0.71/24" ]
#    layer3: true

sonic_portchannel:
  "1":
    description: "management interface"
    interfaces:
      - "1"
      - "2"
    mtu: 1500
    layer3: true
    ips: [ "10.0.0.11/24" ]
  "2":
    description: "redundant access port for management interface loop"
    interfaces:
      - "3"
      - "4"
    vlans:
      - vlan: 2
        mode: "untagged"

sonic_routes:
  - prefix: "8.8.4.4/32"
    nexthop: "10.1.1.1"

# Experimental
sonic_bgp_external: false
#sonic_vtep_src: "172.16.0.1/32"
#sonic_bgp_peers:
#  - "ip": "172.16.99.2"
#    "src_ip": "172.16.99.1"
#    "asn": "4210000002"
#    "name": "underlay to ToR2"
#sonic_vtep_peers:
#  - "ip": "172.16.0.2"
#    "asn": "4210000002"
#    "name": "EVPN overlay to ToR2"
