---
sonic_bgp_ip: "172.16.0.2/32"
sonic_asn: "4210000002"
sonic_interfaces:
  "11":
    description: "bootstrap"
    autoneg: "off"
    fec: "none"
    speed: "10000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "13":
    description: "srx2"
    autoneg: "off"
    fec: "none"
    speed: "1000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "55":
    layer3: true
#   ips: [ "172.16.99.2/24" ]
    description: "ToRSwitch 1 port 55"
sonic_vlans:
  "2":
    vxlan: "10002"
    ips: [ "10.0.0.72/24" ]
    layer3: true
    mtu: 1500

# Experimental
sonic_bgp_external: false
#sonic_vtep_src: "172.16.0.2/32"
#sonic_bgp_peers:
#  - "ip": "172.16.99.1"
#    "src_ip": "172.16.99.2"
#    "asn": "4210000001"
#    "name": "underlay to ToR1"
#sonic_vtep_peers:
#  - "ip": "172.16.0.1"
#    "asn": "4210000001"
#    "name": "EVPN overlay to ToR1"
