---
sonic_vxlan_vtep_ip: "172.16.0.2/32"
sonic_asn: "4210000002"
sonic_interfaces:
  "1":
    layer3: true
    description: "CloudStack1 port 2"
  "2":
    layer3: true
    description: "CloudStack2 port 2"
  "3":
    layer3: true
    description: "CloudStack3 port 2"
  "4":
    layer3: true
    description: "CloudStack4 port 2"
  "5":
    layer3: true
    description: "CloudStack5 port 2"
  "6":
    layer3: true
    description: "CloudStack6 port 2"
  "7":
    layer3: true
    description: "CloudStack7 port 2"
  "8":
    layer3: true
    description: "CloudStack8 port 2"
  "17":
    description: "PortChannel1 MGMT p1"
    autoneg: "off"
    fec: "none"
    speed: "10000"
  "18":
    description: "PortChannel1 MGMT p2"
    autoneg: "off"
    fec: "none"
    speed: "10000"
  "19":
    description: "PortChannel2 MGMTLoop p1"
    autoneg: "off"
    fec: "none"
    speed: "10000"
  "20":
    description: "PortChannel2 MGMTLoop p2"
    autoneg: "off"
    fec: "none"
    speed: "10000"
  "33":
    description: "mgmtsw port 50"
    autoneg: "off"
    fec: "none"
    speed: "10000"
  "41":
    description: "fakeinet ge-0/9"
    autoneg: "off"
    fec: "none"
    speed: "1000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "47":
    description: "fw1 ge-0/9"
    autoneg: "off"
    fec: "none"
    speed: "1000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "48":
    description: "fw2 ge-0/9"
    autoneg: "off"
    fec: "none"
    speed: "1000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "55":
    layer3: true
    description: "torsw1 port 55"
  "56":
    layer3: true
    description: "torsw1 port 56"

sonic_vlans:
  "2":
    vxlan: "10002"
    mtu: 1500
    ips: [ "10.0.0.72/24" ]
    layer3: true

sonic_portchannel:
  "1":
    description: "management interface"
    interfaces:
      - "17"
      - "18"
    mtu: 1500
    layer3: true
    ips: [ "10.1.0.12/24" ]
  "2":
    description: "redundant access port for management interface loop"
    interfaces:
      - "19"
      - "20"
    vlans:
      - vlan: 2
        mode: "untagged"

sonic_routes:
  - prefix: "8.8.4.4/32"
    nexthop: "10.1.1.1"

# Experimental
sonic_bgp_external: false

