---
sonic_bgp_ip: "172.16.0.2/32"
sonic_asn: "4210000002"
sonic_interfaces:
  "1": 
    layer3: true
    description: "CloudStack Node 1"
  "2":
    layer3: true
    description: "CloudStack Node 2"
  "3":
    layer3: true
    description: "CloudStack Node 3"
  "4":
    layer3: true
    description: "CloudStack Node 4"
  "5":
    layer3: true
    description: "CloudStack Node 5"
  "6":
    layer3: true
    description: "CloudStack Node 6"
  "7":
    layer3: true
    description: "CloudStack Node 7"
  "8":
    layer3: true
    description: "CloudStack Node 8"
  "9":
    description: "RJ45 bootstrap port"
    autoneg: "on"
    adv_speeds: "10000,1000,100"
    speed: "10000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "11":
    description: "bootstrap port"
    autoneg: "off"
    speed: "10000"
    vlans:
      - vlan: 2
        mode: "untagged"
  "46":
    layer3: true
    description: "Management Switch"
  "55":
    layer3: true
    description: "ToRSwitch 1 port 55"
  "56":
    layer3: true
    description: "ToRSwitch 1 port 56"
sonic_vlans:
  "2":
    vxlan: "10002"
#    ips: [ "10.0.0.72/24" ]
#    layer3: true
#    mtu: 1500
