---
- name: "ensure ufw service is started and enabled"
  service:
    name: ufw
    state: started
    enabled: true

- name: "open up port {{ ssh_port|default(22) }} for SSHd alternative port"
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port|default(22) }}"
    proto: tcp

- name: "enable UFW and set default policy to disallow incoming"
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming

# Automatic updates
- name: "Automatic updates: {{ 'yes' if base_autoupdate else 'no' }}"
  ansible.builtin.apt:
    name: unattended-upgrades
    state: "{{ 'present' if os_autoupdate else 'absent' }}"

# TODO: Finish automatic updates
