---

# We do this because ansible_inventory isn't quite the right thing to do as that is read from the
# destination machine, and if it hasn't been configured yet, it won't be right.
- name: set host names
  set_fact:
    short_host: "{{ inventory_hostname.split('.')[0] }}"

- name: configure hosts for hostname
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ inventory_hostname }} {{ short_host }}"
    regexp: '^127\.0\.1\.1'
  notify: set_hostname

- name: configure hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: set_hostname

# Move to network config
# - name: configure network interface
#   lineinfile:
#     dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.alias }}
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#     state: "{{ item.state }}"
#     when: ansible_os_family == 'RedHat'
#   with_items:
#     - { regexp: 'DNS1\=*', line: "DNS1=8.8.8.8", state: "present" }
#     - { regexp: 'DNS2\=*', line: "DNS2=8.8.4.4", state: "present" }
#     - { regexp: 'DNS3\=*', line: "",             state: "absent" }

- name: Make sure the superuser is created for management.
  user:
    name: "{{ superuser }}"
    create_home: yes
    shell: "/bin/bash"
    groups: "{{ [ 'wheel', 'users', 'adm', 'lp' ] if ansible_os_family == 'RedHat' else [ 'adm', 'sudo', 'plugdev', 'cdrom', 'dip' ] }}"
    state: present
    append: yes
    password: "{{ superuser_password | password_hash('sha512') }}"
    update_password: on_create
  register: superuser_created

- name: Fetch the hash for the existing superuser password
  script: get_pw_hash.sh "{{ superuser }}"
  register: pwhash
  changed_when: false

- name: Make sure the superuser password is up to date
  user:
    name: "{{ superuser }}"
    password: "{{ superuser_password | password_hash('sha512', pwhash.stdout | trim) }}"
    update_password: always
  register: superuser_pwchanged

- name: Fixup ansible password for this playbook
  set_fact:
    ansible_password: "{{ superuser_password }}"
    ansible_become_pass: "{{ superuser_password }}"
  no_log: true
  when: ansible_user == superuser and (superuser_created.changed or superuser_pwchanged.changed)

- name: disable root user
  user:
    name: root
    password: "!"
    update_password: always

- name: "Ensure /home/{{ superuser }}/.ssh exists"
  file:
    path: "/home/{{ superuser }}/.ssh/"
    state: directory
    mode: 0700
    owner: "{{ superuser }}"
    group: "{{ superuser }}"

- name: "Make sure the public key for ssh authentication is configured for the {{ superuser }} user"
  lineinfile:
    path: "/home/{{ superuser }}/.ssh/authorized_keys"
    state: present
    create: yes
    owner: infra
    group: infra
    mode: 0600
    line: "{{ item }}"
  with_items: "{{ superuser_pubkey }}"
  when: superuser_pubkey is defined

- name: Install packages
  include_tasks: "rhel_packages.yml"
  when: ansible_os_family == 'RedHat'

- name: Debian packages
  include_tasks: "debian_packages.yml"
  when: ansible_os_family == 'Debian'

- name: check if systemd-timesyncd is installed
  shell: systemctl status systemd-timesyncd
  register: timesyncd_status
  failed_when: not (timesyncd_status.rc == 4 or timesyncd_status.rc == 3 or timesyncd_status.rc == 0)
  changed_when: False

- name: disable systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: stopped
    enabled: no
  when: (timesyncd_status == 3 or timesyncd_status == 0)

- name: install /etc/chrony.conf
  template:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: chrony_restart

- name: ensure chronyd is started and enabled
  service:
    name: chronyd
    state: started
    enabled: true

- name: Set timezone
  file:
    path: /etc/localtime
    src: "/usr/share/zoneinfo/{{ timezone }}"
    state: link

- name: install /etc/ssh/sshd_config
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    backup: true
  notify: sshd_restart

- name: Ensure we update the ssh port if it was changed
  set_fact:
    ansible_ssh_port: "{{ ssh_port }}"
  when: ansible_ssh_port != ssh_port

# Rsyslog recommends using imuxsock, so that means we need ForwardToSyslog
# and we want to otherwise make journald unused as we don't want stuff to persist.
# https://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html
- name: configure journald settings (/etc/systemd/journald.conf)
  ini_file:
    dest: /etc/systemd/journald.conf
    section: Journal
    option: "{{ item.key }}"
    value: "{{ item.val }}"
  with_items:
    - { key: "RateLimitIntervalSec", val: "0" }
    - { key: "RateLimitBurst",       val: "0" }
    - { key: "RuntimeMaxUse",        val: "100M" }
    - { key: "Storage",              val: "volatile" }
    - { key: "ForwardToSyslog",      val: "true" }
    - { key: "MaxLevelSyslog",       val: "debug" }
    - { key: "MaxRetentionSec",      val: "2h" }
  notify: journald_restart

- name: install /etc/rsyslog.conf
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify: rsyslog_restart

- name: add compress to /etc/logrotate.conf
  lineinfile:
    dest: /etc/logrotate.conf
    insertafter: "# uncomment this if you want your log files compressed"
    line: compress
  notify: rsyslog_restart

- name: configure logrotate
  copy:
    src: logrotate_rsyslog
    dest: /etc/logrotate.d/syslog
    owner: root
    group: root
    mode: 0644

- name: install custom prompt for shell access
  copy:
    src: 99-prompt.sh
    dest: /etc/profile.d/99-prompt.sh
    owner: root
    group: root
    mode: 0644

- name: Put /usr/local/bin in default path
  copy:
    src: profile_local_paths.sh
    dest: /etc/profile.d/local_paths.sh
    owner: root
    group: root
    mode: 0644

- name: install idle timeout
  copy:
    src: tout.sh
    dest: /etc/profile.d/tout.sh
    owner: root
    group: root
    mode: 0644

- name: automatically perform discard/trim operations weekly to free up disk space
  copy:
    src: trim.sh
    dest: /usr/local/bin/trim.sh
    owner: root
    group: root
    mode: 0755

- name: insert link in /etc/cron.weekly for discard/trim
  file:
    src: /usr/local/bin/trim.sh
    dest: /etc/cron.weekly/trim
    state: link

- name: fix MAILTO in /etc/crontab
  lineinfile:
    dest: /etc/crontab
    regexp: MAILTO
    line: "MAILTO={{ admin_email }}"
    backrefs: true

- name: configure exim
  template:
    src: exim.conf
    dest: "{{ '/etc/exim/exim.conf' if ansible_os_family == 'RedHat' else '/etc/exim4/exim4.conf' }}"
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: make sure exim doesn't start, we don't need the daemon
  service:
    name: "{{ 'exim' if ansible_os_family == 'RedHat' else 'exim4' }}"
    state: stopped
    enabled: no

- name: Perform RHEL-specific tasks
  include_tasks: "rhel_tasks.yml"
  when: ansible_os_family == 'RedHat'

- name: Perform Debian-specific tasks
  include_tasks: "debian_tasks.yml"
  when: ansible_os_family == 'Debian'

- name: "fail2ban: create /etc/fail2ban/jail.d/sshd.local file"
  template:
    src: fail2ban_sshd.local
    dest: /etc/fail2ban/jail.d/sshd.local
    owner: root
    group: root
    mode: 0600
  notify: fail2ban_restart

- name: "fail2ban: create directory - /var/run/fail2ban"
  file:
    path: /var/run/fail2ban
    state: directory
    seuser: "{{ 'system_u' if ansible_os_family == 'RedHat' }}"
    setype: "{{ 'fail2ban_var_run_t' if ansible_os_family == 'RedHat' }}"
    owner: root
    group: root
    mode: 0755
  notify: fail2ban_restart

- name: "fail2ban: start and enable"
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Perform CIS hardening
  include_tasks: "cis.yml"

- name: "RedHat: check if server needs rebooting"
  command: "needs-restarting -r"
  notify: reboot
  register: reboot_req
  changed_when: (reboot_req.rc == 1)
  failed_when: (reboot_req.rc > 1)
  when: ansible_os_family == 'RedHat'

- name: "Debian: check if server needs rebooting"
  stat: path=/var/run/reboot-required
  notify: reboot
  register: reboot_req
  changed_when: reboot_req.stat.exists
  when: ansible_os_family == 'Debian'

- name: "Debian: check if any installed services or sessions may need to be restarted"
  shell: "needrestart -r l -b | grep -e NEEDRESTART-SVC -e NEEDRESTART-SESS"
  register: reboot_req
  failed_when: false
  changed_when: reboot_req.rc == 0
  notify: reboot

# We want to flush any handlers for the base role before executing any other
# roles as other roles may perform tasks like bootstrapping a cluster which
# a node reboot after package updates might invalidate such bootstrapping.
- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

