---
- name: install apache/mod_ssl
  dnf:
    name: [ "httpd", "mod_ssl", "mod_http2" ]
    state: latest

- name: Install ACME/mod_md for letsencrypt support
  dnf:
    name: [ "mod_md" ]
    state: "{{ 'installed' if apache_letsencrypt else 'absent' }}"

- name: open up http ports
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}"
    state: enabled
  with_items:
    - "80/tcp"
    - "443/tcp"

- include_tasks: "{{ playbook_dir }}/common/tasks/commentfile.yml"
  loop_control:
    loop_var: commentfile
  with_items:
    - { path: "/etc/httpd/conf.d/welcome.conf",   notify: "httpd_restart" }
    - { path: "/etc/httpd/conf.d/userdir.conf",   notify: "httpd_restart" }
    - { path: "/etc/httpd/conf.d/autoindex.conf", notify: "httpd_restart" }

- name: set proper ssl options
  template:
    src: http_ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: add security settings
  copy:
    src: http_security.conf
    dest: /etc/httpd/conf.d/security.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: enable http2 support
  copy:
    src: http_http2.conf
    dest: /etc/httpd/conf.d/http2.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: configure logging to go to syslog
  copy:
    src: http_log.conf
    dest: /etc/httpd/conf.d/log.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

- name: enable compression for text resources
  copy:
    src: http_deflate.conf
    dest: /etc/httpd/conf.d/deflate.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart

# See https://www.server-world.info/en/note?os=CentOS_8&p=httpd2&f=1
- name: Support ACME authentication for letsencrypt via mod_md
  template:
    src: http_acme.conf
    dest: /etc/httpd/conf.d/acme.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd_restart
  when: apache_letsencrypt

- name: Ensure ACME is not configured if letsencrypt is not enabled
  file:
    path: /etc/httpd/conf.d/acme.conf
    state: absent
  notify: httpd_restart
  when: not apache_letsencrypt

- name: Allow httpd to connect outbound (needed for letsencrypt)
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: SELinux module for mod_md (needed for letsencrypt)
  import_tasks: "{{ playbook_dir }}/common/tasks/semodule.yml"
  vars:
    selinux_module_name: httpd-md
    selinux_module_file: selinux_httpd_mod_md.pp
  when: apache_letsencrypt

- name: comment out error log setting in httpd.conf
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: ErrorLog
    line: '# ErrorLog "logs/error_log"'
  notify: httpd_restart

- name: add web logging config to /etc/rsyslog.conf
  copy:
    src: rsyslog_apache.conf
    dest: /etc/rsyslog.d/apache.conf
    owner: root
    group: root
    mode: 0644
  notify: rsyslog_restart

- name: logrotate for httpd
  copy:
    src: logrotate_http
    dest: /etc/logrotate.d/http
    owner: root
    group: root
    mode: 0644

- name: systemd - enable and start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: install apache fail2ban rules
  copy:
    src: fail2ban_apache.local
    dest: /etc/fail2ban/jail.d/apache.local
    owner: root
    group: root
    mode: 0600
  notify: fail2ban_restart
